#!/bin/bash

process="$1"
service=$(ps -ef|grep "$process"|grep -v grep|grep -v $0 | wc -l)

if [ $service -ne 0 ]
then
        echo "$process is  running"
else
        echo "$process is not running"
fi

